#!/usr/bin/env bash
#
# Download and run main script

set -e
tmp='/tmp/cas'

# Check archiso
if [[ ! -d '/run/archiso' ]]; then
  echo '! Your archiso looks strange'
  echo '- Press ENTER to continue anyway'
  read -r cntn && unset cntn
fi

# Configure live system
curl -f "https://raw.githubusercontent.com/nedorazrab0/cas/main/cfg/etc/\
sysctl.d/99-cust.conf" | sysctl -p - || true

mkdir -p /etc/systemd/{resolved,timesyncd}.conf.d

curl -f "https://raw.githubusercontent.com/nedorazrab0/cas/main/cfg/etc/\
systemd/resolved.conf.d/cust.conf" -o /etc/systemd/resolved.conf.d/cust.conf

curl -f "https://raw.githubusercontent.com/nedorazrab0/cas/main/cfg/etc/\
systemd/timesyncd.conf.d/ntp.conf" -o /etc/systemd/timesyncd.conf.d/ntp.conf

systemctl restart systemd-{timesyncd,resolved,networkd}

# Main
[[ -d "${tmp}" ]] && rm -rf "${tmp}"
mkdir -p "${tmp}"
curl -fL "https://github.com/nedorazrab0/cas/releases/download/\
rolling/cas.tar.lz4" | lz4 -dvc | bsdtar -x -C "${tmp}"

exec bash "${tmp}/main"
